"""
tools/roadmap.py — Roadmap store and domain logic.

Single responsibility: CRUD for roadmaps with step tracking.

Backed by AtomicJSONStore (tools/store_base.py):
  - O(1) get by roadmap_id (in-memory index).
  - O(1) get by entity_id (secondary index — one active roadmap per entity).
  - Atomic disk writes — no partial state on crash.
  - Loads from disk once.

Public interface is identical to the previous version — no callers need to change.

A Roadmap is created when David approves participation in an event or grant.
It contains a checklist of time-bound steps generated by Phi, working
backwards from the entity's deadline.
"""
from __future__ import annotations

import uuid
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

from tools.store_base import AtomicJSONStore

_ROADMAPS_FILE = Path(__file__).parent.parent / "data" / "roadmaps.json"

STEP_CATEGORIES = {"research", "prep", "outreach", "submit", "logistics"}
ROADMAP_STATUSES = {"active", "archived"}


def _now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()[:19] + "Z"


def _validate_step(step: dict) -> None:
    """Raise ValueError if a step dict is structurally invalid."""
    required = {"id", "title", "due_date", "category", "done"}
    missing = required - step.keys()
    if missing:
        raise ValueError(f"Step missing required fields: {missing}")
    if step["category"] not in STEP_CATEGORIES:
        raise ValueError(
            f"Invalid step category '{step['category']}'. Valid: {STEP_CATEGORIES}"
        )


# ── Store with entity_id secondary index ──────────────────────────────────────

class _RoadmapStore(AtomicJSONStore):
    """
    Roadmap store with secondary index: entity_id → roadmap_id (active only).
    One active roadmap per entity is enforced at the application layer (create).
    """

    def __init__(self, path: Path) -> None:
        self._entity_index: dict[str, str] = {}   # entity_id → roadmap_id (active)
        super().__init__(path, id_field="id")

    def _on_load(self, records: list[dict]) -> None:
        self._entity_index = {}
        for r in records:
            self._index_add(r)

    def _on_record_added(self, record: dict) -> None:
        self._index_add(record)

    def _on_record_removed(self, record: dict) -> None:
        eid = record.get("entity_id")
        rid = record.get("id")
        if eid and self._entity_index.get(eid) == rid:
            self._entity_index.pop(eid, None)

    def _index_add(self, r: dict) -> None:
        eid = r.get("entity_id")
        rid = r.get("id")
        if eid and rid and r.get("status") == "active":
            self._entity_index[eid] = rid
        elif eid and rid and r.get("status") != "active":
            # Remove stale active entry if this is now archived
            if self._entity_index.get(eid) == rid:
                self._entity_index.pop(eid, None)

    def active_id_for_entity(self, entity_id: str) -> str | None:
        with self._lock:
            self._ensure_loaded()
            return self._entity_index.get(entity_id)


# Module-level singleton
_store = _RoadmapStore(_ROADMAPS_FILE)


# ── Public API (identical interface to previous version) ──────────────────────

def create(
    entity_id: str,
    entity_name: str,
    entity_type: str,
    deadline: str,
    deadline_label: str,
    steps: list[dict],
    registration_url: Optional[str] = None,
) -> dict:
    """
    Create and persist a new roadmap. Returns the created roadmap dict.
    Raises ValueError if any step is invalid.
    """
    for step in steps:
        _validate_step(step)

    roadmap = {
        "id":               "rm_" + uuid.uuid4().hex[:8],
        "entity_id":        entity_id,
        "entity_name":      entity_name,
        "entity_type":      entity_type,
        "deadline":         deadline,
        "deadline_label":   deadline_label,
        "registration_url": registration_url,
        "status":           "active",
        "steps":            steps,
        "created_at":       _now_iso(),
        "updated_at":       _now_iso(),
    }
    _store.put(roadmap)
    return dict(roadmap)


def list_active() -> list[dict]:
    """Return all roadmaps with status='active', sorted by deadline ascending."""
    active = _store.filter(lambda r: r.get("status") == "active")
    active.sort(key=lambda r: r.get("deadline") or "9999-99-99")
    return active


def list_all() -> list[dict]:
    """Return all roadmaps regardless of status."""
    return _store.all()


def get(roadmap_id: str) -> Optional[dict]:
    """O(1) lookup by roadmap id."""
    return _store.get(roadmap_id)


def get_by_entity(entity_id: str) -> Optional[dict]:
    """Return the active roadmap for an entity, or None. O(1) via index."""
    rid = _store.active_id_for_entity(entity_id)
    return _store.get(rid) if rid else None


def update_step(roadmap_id: str, step_id: str, done: bool) -> bool:
    """Toggle a step's done state. Returns True if found and updated."""
    with _store._lock:
        _store._ensure_loaded()
        roadmap = _store._records.get(roadmap_id)
        if roadmap is None:
            return False
        for step in roadmap.get("steps", []):
            if step.get("id") == step_id:
                step["done"] = done
                roadmap["updated_at"] = _now_iso()
                _store._flush()
                return True
    return False


def archive(roadmap_id: str) -> bool:
    """Mark a roadmap as archived. Returns True if found."""
    with _store._lock:
        _store._ensure_loaded()
        roadmap = _store._records.get(roadmap_id)
        if roadmap is None:
            return False
        old = dict(roadmap)
        _store._on_record_removed(old)
        roadmap["status"] = "archived"
        roadmap["updated_at"] = _now_iso()
        _store._on_record_added(roadmap)
        _store._flush()
    return True


def days_until_deadline(deadline_iso: str) -> Optional[int]:
    """
    Return full days until the given ISO date (YYYY-MM-DD).
    Returns None if unparseable. Negative if deadline is in the past.
    """
    try:
        target = datetime.fromisoformat(deadline_iso)
        return (target.date() - datetime.now().date()).days
    except (ValueError, AttributeError):
        return None
